### ISSUE TITLE
Support for ToggleTerm

### ISSUE THREAD

**Issue by Integralist** [samjwill/nvim-unception#24]
👋🏻 

I just installed this plugin, and noticed that if I open a floating terminal using https://github.com/akinsho/toggleterm.nvim then it will open the file in the floating terminal window but without any of the usual neovim layout (e.g. status bar, line numbers).

Then I noticed this happened even in a vertical split terminal. 

What's happening here? Is there configuration I should set or is this expected behaviour?

Thanks!

## Screenshots

<img width="557" alt="Screenshot 2022-10-26 at 19 49 15" src="https://user-images.githubusercontent.com/180050/198111313-9fb7a4d2-1bcd-4e59-a42b-9ba43b54958c.png">

<img width="1920" alt="Screenshot 2022-10-26 at 19 49 50" src="https://user-images.githubusercontent.com/180050/198111338-7bb9de05-993f-44f0-b32c-fe84a69685eb.png">

**Comment by samjwill** [comment]
Hello!

That is odd! I just recently made some tweaks to the wiki on setting it up to work with terminal toggling plugins [here](https://github.com/samjwill/nvim-unception/wiki/Setup-with-terminal-toggling-plugins!).

I just tried ToggleTerm out, and did experience some funky behavior when the `direction` was left as its default value, but with the direction set to `float`, it seemed to work fine. I suspect that the behavior I experienced was a quirk/bug in ToggleTerm itself, but I didn't reproduce the behavior I'm seeing in your screenshot though. Not 100% sure what's happening there.

The keymap I set to get ToggleTerm working was different from what's in the wiki though. It was
```
vim.keymap.set('t', '<C-\\><C-N>', '<C-\\><C-N><CMD>ToggleTerm<CR>')
```

Let me know if this helps!
