### ISSUE TITLE
Weird interaction with Noice.nvim in git commit buffers opened from builtin terminal

### ISSUE THREAD

**Issue by cultab** [samjwill/nvim-unception#36]
I don't know how I missed in when testing in #25, making a separate issue since it only happens with Noice.nvim.
Only happens with in git commit buffers when entering command mode (Noice.nvim opens a floating window to write in).

Error log:
```
Error detected while processing BufUnload Autocommands for "*":
E5108: Error executing lua ...ker/start/nvim-unception/lua/common/common_functions.lua:25: attempt to concatenate local 'dir_path' (a nil value)
stack traceback:
    ...ker/start/nvim-unception/lua/common/common_functions.lua:25: in function 'get_absolute_filepath'
    ...ker/start/nvim-unception/lua/server/server_functions.lua:8: in function 'unception_handle_unloaded_buffer'
    [string ":lua"]:1: in main chunk
    [C]: at 0x556424c6a200
    [C]: in function 'pcall'
    ...ack/packer/start/noice.nvim/lua/noice/view/scrollbar.lua:71: in function 'hide'
    ...ack/packer/start/noice.nvim/lua/noice/view/scrollbar.lua:101: in function 'update'
    ...ack/packer/start/noice.nvim/lua/noice/view/scrollbar.lua:64: in function 'show'
    ...site/pack/packer/start/noice.nvim/lua/noice/view/nui.lua:277: in function <...site/pack/packer/start/noice.nvim/lua/noice/view/nui.lua:251
    [C]: in function 'xpcall'
    ...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
    ...ite/pack/packer/start/noice.nvim/lua/noice/view/init.lua:123: in function 'display'
    ...ack/packer/start/noice.nvim/lua/noice/message/router.lua:115: in function <...ack/packer/start/noice.nvim/lua/noice/message/router.lua:74>
    [C]: in function 'xpcall'
    ...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
    .../site/pack/packer/start/noice.nvim/lua/noice/ui/init.lua:42: in function <.../site/pack/packer/start/noice.nvim/lua/noice/ui/init.lua:26>
```

It seems get_absolute_path() (from common_functions.lua) is being called with fake relative paths like:
```
noice://24/
noice://25/scrollbar
noice://25/
noice://26/scrollbar
noice://26/
noice://27/scrollbar
noice://27/
```

and so vim.loop.fs_realpath(dir_path) returns `nil` for those paths.

From limited testing it _seems_ just checking if the return is nil and not concatenating the now `nil` `dir_path` to `absolute_path` (leaving `absolute_path` be `nil`, fixes this, but I am not familiar with how get_absolute_path() is used to know if returning nil is fine.

**Comment by samjwill** [comment]
Wow, thanks for the wonderful error report! Points me right where I need to look.

I'll take a look at this when I get some free time.

**Comment by samjwill** [comment]
I think I was able to reproduce this issue without any plugins by deleting a terminal buffer (which has the path `term:///my_dir/...`) while a commit message was pending. I think #38 remedies this issue?

**Comment by cultab** [comment]
Yes, just updated and it has been resolved!
