### ISSUE TITLE
Unexpected error message with g:unception_block_while_host_edits enabled

### ISSUE THREAD

**Issue by jamesb6626** [samjwill/nvim-unception#71]
Since commit 2ff9b2374e270ef833f212b939356a3b220a3ecf (bisected), I get the following error whenever I start nvim without exactly one argument:

```
Error detected while processing /home/james/.vim/.plugged/nvim-unception/plugin/main.lua:
Must have exactly 1 argument when g:unception_block_while_host_edits is enabled!
```

I have the following unception settings:

```
let g:unception_open_buffer_in_new_tab = v:true
let g:unception_block_while_host_edits = v:true
```

If you'd like the whole rc files or have difficulty reproducing, I'll strip it down to a minimal one with just unception, mine is quite messy.

I prefer things to block by default, since I don't know where the editor might end up being used, e.g. sudoedit or git (separately, it might be useful to have a command to unblock too, in case we don't want to get rid of the buffer).
But I think this error is only supposed to occur for a client rather than the host, unless I misunderstood.
Aren't only the clients supposed to receive exactly one argument?
I don't think the restriction was supposed to apply to the host, unception isn't supposed to mess with the host arguments is it?

**Comment by samjwill** [comment]
Your assumption is correct. That's a bug. Should be good now. Thanks for the error report.
