### ISSUE TITLE
Support passing multiple filepath arguments at once.

### ISSUE THREAD

**Issue by samjwill** [samjwill/nvim-unception#73]
I think this used to work, but probably broke when I refactored the way that I was sending the edit command. It used to be a full vimscript string that was sent to the host session.

**Comment by dmtrKovalenko** [comment]
But what about supporting the ability to use nvim -d it appeals to be able to display 2 windows.

**Comment by samjwill** [comment]
I think that's not exactly within the scope I had initially intended when I opened this issue, so you can open another one if you want to. I'm not sure how I would go about supporting other nvim arguments with the current design in a robust way to be perfectly honest. See [this blurb](https://github.com/samjwill/nvim-unception/blob/0cbf11a6c5c4314e88245b69d460f85f30885d2e/README.md?plain=1#L91-L100) in the README.

I would guess that I'd have to do something like implement a parsing mechanism that handles every flag in a specific way server-side (e.g. search the string for the occurrence of any flags, then if I found the `-d` flag, I'd open a new tab and then open both buffers in a vertical split or something along those lines, if I found the `-b` flag, I'd have to find a way to open the individual itself in binary mode, which might or might not be possible, etc. etc.). It'd be a pretty substantial amount of work to do this way, and I'm not sure that I currently have the bandwidth to do so.

If you have a better idea for how you'd accomplish it though, I'd definitely be willing to hear it out. Alternatively, you could take a look at https://github.com/willothy/flatten.nvim, which is based on unception, but re-written to behave somewhat differently, to see if that's more conducive to what you're trying to accomplish.
