### ISSUE TITLE
Issue with man pages

### ISSUE THREAD

**Issue by AckslD** [samjwill/nvim-unception#76]
Loving this plugin! :rocket:

One issue I have is that I use `MANPAGER='nvim +Man!' to use `nvim` for man pages. However if I run `man nvim` in a `nvim`-terminal I just get an empty buffer. Any idea how to solve this?

**Comment by samjwill** [comment]
I might not have time to look into this for a bit. One thing that you could do as a band-aid is set the man pager to also pass the flag to [disable unception](https://github.com/samjwill/dotfiles/blob/c59477c47867fb8f5560ba01d17722443428bc7e/.gitconfig#L5) in addition to the `+Man` flag. That should at least allow you to open a man page, even if it's nested.

**Comment by AckslD** [comment]
Thanks for the suggestion @samjwill! I tried setting:
```
export MANPAGER="nvim +'let g:unception_disable=1' +Man!"
```
instead but still getting the same behaviour unfortunately. Any thoughts of why that might be? But no problem at all if you don't have the time :)

**Comment by samjwill** [comment]
Alternatively, I know the developer for [nvim-flatten](https://github.com/willothy/flatten.nvim/), which is based on unception with some feature additions/code tweaks, was working on support for piping text. There might be something you can throw together to pipe text directly into a Neovim buffer using that and set the file type to a man page for syntax highlighting.

**Comment by AckslD** [comment]
Thanks a lot for the input, really appreciate it! I'll try this out and see if I can get it working 👍

**Comment by AckslD** [comment]
Thanks again @samjwill, using `--cmd` indeed did the trick. I hadn't realised that `+` and `--cmd` are executed at different times. It indeed creates nested sessions but I can at least now open the man pages like this again.

**Comment by AckslD** [comment]
I also tried setting my `MANPAGER` to a bash script of the form:
```
file=$(mktemp)
cat > $file
nvim +Man! $file
```
which at least opens the man page but the `Man!` command is not passed to the original session so the formatting is off.
